# Site settings
title: Nothing but the Objectivetruth
email: miguel@objectivetruth.ca
description: > # this means to ignore newlines until "baseurl:"
  Musing from a Senior Developer and Team Lead with a background in Sales, Biosciences and now Computer Science.
  Trying to save the world one Machine Learning app at a time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.objectivetruth.ca" # the base hostname & protocol for your site
github_username:  Objectivetruth
sass: 
    style: :compressed
paginate: 5
paginate_path: "/archives/page:num"
# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]

gems:
    - jemoji
